input{
    kafka{
        bootstrap_servers => "kafka:9092"
        topics => ["LOGIN-ACTIVITY-LOGS", "TOKEN-REFRESH-ACTIVITY-LOGS"]
        group_id => "logstash-consumer"
        codec => "json"
        decorate_events => true
    }
}
filter{
    mutate{
        copy => {"@timestamp" => "created_at"}
    }
    ruby{
            code => "
                kafka_topic = event.get('[@metadata][kafka][topic]')
                event.set('log_type',kafka_topic) if kafka_topic
            "
        }
}
output{
    elasticsearch{
        hosts => ["http://elasticsearch:9200"]
        index => "checklist-logs-%{+YYYY.MM.dd}"
    }
    stdout{
        codec => rubydebug
    }
}